### ISSUE TITLE
test of findorf giving errors

### ISSUE THREAD

**Issue by nldowell** [vsbuffalo/findorf#1]
Hello Vince Buffalo,

I came across your findorf program and it looks quite useful.  I cloned the repository and ran the install.  No errors were thrown.  I tried to run a test of 'findorf join' of ~20 contigs against their BLASTX results and the following errors printed out:

$ findorf join --ref ../seqGrab/pla2Fam.uniqHits.fasta un:pla2Fam.xml
[join] loading all contig sequences...  done.
[join] processing BLAST file 'un'...    Traceback (most recent call last):
  File "/usr/local/bin/findorf", line 9, in <module>
    load_entry_point('findorf==1.5', 'console_scripts', 'findorf')()
  File "/usr/local/lib/python2.7/dist-packages/findorf-1.5-py2.7.egg/findorf/findorf.py", line 141, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/findorf-1.5-py2.7.egg/findorf/findorf.py", line 41, in _join_relative_results
    contigs = add_blastx_results(args.ref, args.blastx)
  File "/usr/local/lib/python2.7/dist-packages/findorf-1.5-py2.7.egg/findorf/blast.py", line 92, in add_blastx_results
    for record in NCBIXML.parse(blast_file):
  File "/usr/lib/pymodules/python2.7/Bio/Blast/NCBIXML.py", line 652, in parse
    expat_parser.Parse(text, False)  
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 124582, column 178

Any suggestions on what I may be doing wrong would be greatly appreciated. Thanks in advance.

Noah

**Comment by vsbuffalo** [comment]
Did you use legacy BLAST or BLAST+? findorf only works with the latter. Make sure our BLAST+ output is XML and you are using the newest version on BioPython.

**Comment by nldowell** [comment]
I am using BLAST+ with outfmt = 5 which should be XML.

BioPython should be new since I installed today but I will see if it has
something to do with that install.

thanks for the reply.

**Comment by nldowell** [comment]
I re-installed BioPython from source after building the BioPython dependencies.  
findorf is working now.

Thanks for making this available!
