### ISSUE TITLE
findorf giving errors

### ISSUE THREAD

**Issue by yandazeng** [vsbuffalo/findorf#4]
Hello Vince Buffalo,

the findorf program is very useful for me , but when i tried to use it ,it always send errors. 
My linux os is ubuntu  biolinux 7, python version is 2.7, biopython is 1.6, Numpy is installed also
xml file is from the result of Blast+,  

[join] loading all contig sequences...  done.
[join] processing BLAST file 'Gr'...    Traceback (most recent call last):
  File "../../Downloads/findorf-master/findorf/findorf.py", line 144, in <module>
    contigs = main()
  File "../../Downloads/findorf-master/findorf/findorf.py", line 141, in main
    args.func(args)
  File "../../Downloads/findorf-master/findorf/findorf.py", line 41, in _join_relative_results
    contigs = add_blastx_results(args.ref, args.blastx)
  File "/home/zeng/Downloads/findorf-master/findorf/blast.py", line 93, in add_blastx_results
    for record in NCBIXML.parse(blast_file):
  File "/usr/local/lib/python2.7/dist-packages/Bio/Blast/NCBIXML.py", line 603, in parse
    expat_parser.Parse("", True)  # End of XML record
xml.parsers.expat.ExpatError: no element found: line 1734169, column 0

the line 1734169 is the end of xml file, but it always raise error from it .what should i do? 

Any suggestions on what I may be doing wrong would be greatly appreciated. Thanks in advance.

yanda

**Comment by vsbuffalo** [comment]
It sounds like your XML is improperly formatted or truncated. Could you find a _very small_ example XML file that still errors out in the same way and send it?

**Comment by yandazeng** [comment]
@vsbuffalo Thanks for your suggestion, There do have some errors during the formation of XML file.
Findorf is  working now when i moved the errors in XML file. 
Thank you very much!
